# Fish Shell Configuration
# Generated by 000-dotfiles TUI Installer
# https://fishshell.com/docs/current/

# =============================================================================
# PATH Configuration
# =============================================================================

# Add ~/.local/bin (pip packages, fnm, npm globals, cargo, etc.)
fish_add_path -g $HOME/.local/bin

# Cargo (Rust)
if test -d $HOME/.cargo/bin
    fish_add_path -g $HOME/.cargo/bin
end

# Go
if test -d $HOME/go/bin
    fish_add_path -g $HOME/go/bin
end
if test -d /usr/local/go/bin
    fish_add_path -g /usr/local/go/bin
end

# =============================================================================
# Environment Variables
# =============================================================================

# Editor preference
set -gx EDITOR vim
if command -q nvim
    set -gx EDITOR nvim
end

# Less options
set -gx LESS '-R --mouse --wheel-lines=3'

# =============================================================================
# Tool Completions
# =============================================================================

# uv (Python package manager)
if command -q uv
    uv generate-shell-completion fish | source
end

# gh (GitHub CLI)
if command -q gh
    gh completion -s fish | source
end

# gum (TUI component library)
if command -q gum
    gum completion fish | source
end

# glow (Markdown renderer)
if command -q glow
    glow completion fish | source
end

# fnm (Fast Node Manager)
if command -q fnm
    fnm env --use-on-cd --shell fish | source
end

# direnv (per-project environment variables)
if command -q direnv
    direnv hook fish | source
end

# =============================================================================
# Modern CLI Aliases
# =============================================================================

# bat (better cat) - https://github.com/sharkdp/bat
if command -q bat
    alias cat 'bat --paging=never'
    alias catp 'bat'  # cat with paging
end

# eza (better ls) - https://github.com/eza-community/eza
if command -q eza
    alias ls 'eza --icons --group-directories-first'
    alias ll 'eza -l --icons --group-directories-first --git'
    alias la 'eza -la --icons --group-directories-first --git'
    alias lt 'eza --tree --icons --level=2'
    alias lta 'eza --tree --icons -a --level=2'
end

# fd (better find) - https://github.com/sharkdp/fd
if command -q fd
    alias find 'fd'
end

# ripgrep (better grep) - https://github.com/BurntSushi/ripgrep
if command -q rg
    alias grep 'rg'
end

# zoxide (better cd) - https://github.com/ajeetdsouza/zoxide
if command -q zoxide
    zoxide init fish | source
end

# =============================================================================
# Useful Functions
# =============================================================================

# Create directory and cd into it
function mkcd
    mkdir -p $argv[1] && cd $argv[1]
end

# Quick navigation up directories
function ..
    cd ..
end
function ...
    cd ../..
end
function ....
    cd ../../..
end

# =============================================================================
# Greeting
# =============================================================================

# Disable default greeting
set -g fish_greeting

# Optional: Show fastfetch on new interactive shell
# if status is-interactive && command -q fastfetch
#     fastfetch
# end
